title: Privacidade Digital - Encriptação Contra a Vigilância Global em Massa
description: Você está sendo vigiado. Equipe-se com conhecimento, encriptação e privacidade para resistir à vigilância global em massa.
url: "https://www.privacidade.digital"
sass:
  style: compressed
plugins:
  - jekyll-sitemap
sitemap:
file: "/sitemap.xml"
include: [".well-known"]
