title: Privacidade Digital - Encriptação Contra Vigilância Global em Massa
description: Você está sendo vigiado. Ferramentas de conhecimento, encriptação e privacidade para protegê-lo contra vigilância global em massa.
url: "https://www.privacidade.digital"
sass:
  style: compressed
plugins:
  - jekyll-sitemap
sitemap:
file: "/sitemap.xml"
include: [".well-known"]
