title: Privacidade.Digital — Criptografia Contra a Vigilância Global em Massa
name: Privacidade.Digital
description: Você está sendo vigiado. Equipe-se com conhecimento, criptografia e privacidade para resistir à vigilância global em massa.
url: "https://Privacidade.Digital"
production_url: "https://Privacidade.Digital"
sass:
  style: compressed
plugins:
  - jekyll-sitemap
sitemap:
file: "/sitemap.xml"
include: [".well-known"]
exclude: ["font", "vendor"]
